-- Add signup token columns to profiles table for magic link signup
-- This allows admins to generate unique signup links for guests

ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS signup_token TEXT,
ADD COLUMN IF NOT EXISTS signup_token_expires_at TIMESTAMPTZ;

-- Create index for efficient token lookups
CREATE INDEX IF NOT EXISTS profiles_signup_token_idx ON profiles(signup_token) 
WHERE signup_token IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN profiles.signup_token IS 'Unique token for magic link signup. Generated by admin and used in /signup/[profileId]/[token] URLs.';
COMMENT ON COLUMN profiles.signup_token_expires_at IS 'Expiration timestamp for the signup token. Tokens expire after 30 days by default.';

