export const HEADBANDS_CATEGORIES = [
  { id: 'random', label: 'Random (all 200)', emoji: '🎲' },
  { id: 'nfl', label: 'NFL / American Football', emoji: '🏈' },
  { id: 'football', label: 'Football / Sports', emoji: '⚽' },
  { id: 'video_games', label: 'Video Games', emoji: '🎮' },
  { id: 'tech', label: 'Tech / PC / Gaming', emoji: '🖥' },
  { id: 'board_games', label: 'Board Games', emoji: '🎲' },
  { id: 'mario_kart', label: 'Mario Kart / Nintendo', emoji: '🏎' },
  { id: 'star_wars', label: 'Star Wars', emoji: '🌌' },
  { id: 'lotr', label: 'Lord of the Rings', emoji: '🧝' },
  { id: 'pop_culture', label: 'Pop Culture / Celebrities', emoji: '🌍' },
  { id: 'general', label: 'General Knowledge / Fun', emoji: '🌎' },
] as const

export type HeadbandsCategoryId = typeof HEADBANDS_CATEGORIES[number]['id']

export interface HeadbandsItem {
  text: string
  category: HeadbandsCategoryId
}

export const HEADBANDS_ITEMS: HeadbandsItem[] = [
  { text: 'Tom Brady', category: 'nfl' },
  { text: 'Patrick Mahomes', category: 'nfl' },
  { text: 'Travis Kelce', category: 'nfl' },
  { text: 'Aaron Rodgers', category: 'nfl' },
  { text: 'Josh Allen', category: 'nfl' },
  { text: 'Joe Burrow', category: 'nfl' },
  { text: 'Lamar Jackson', category: 'nfl' },
  { text: 'Justin Jefferson', category: 'nfl' },
  { text: 'Dallas Cowboys', category: 'nfl' },
  { text: 'Kansas City Chiefs', category: 'nfl' },
  { text: 'Super Bowl', category: 'nfl' },
  { text: 'Touchdown', category: 'nfl' },
  { text: 'Quarterback', category: 'nfl' },
  { text: 'Helmet', category: 'nfl' },
  { text: 'End Zone', category: 'nfl' },
  { text: 'Lionel Messi', category: 'football' },
  { text: 'Cristiano Ronaldo', category: 'football' },
  { text: 'Neymar', category: 'football' },
  { text: 'Erling Haaland', category: 'football' },
  { text: 'Kylian Mbappé', category: 'football' },
  { text: 'Premier League', category: 'football' },
  { text: 'Referee', category: 'football' },
  { text: 'Goalkeeper', category: 'football' },
  { text: 'VAR', category: 'football' },
  { text: 'Red Card', category: 'football' },
  { text: 'Yellow Card', category: 'football' },
  { text: 'Penalty Kick', category: 'football' },
  { text: 'Corner Kick', category: 'football' },
  { text: 'World Cup', category: 'football' },
  { text: 'Football Manager', category: 'football' },
  { text: 'Michael Jordan', category: 'football' },
  { text: 'Usain Bolt', category: 'football' },
  { text: 'Serena Williams', category: 'football' },
  { text: 'Tiger Woods', category: 'football' },
  { text: 'Novak Djokovic', category: 'football' },
  { text: 'Battlefield', category: 'video_games' },
  { text: 'Battlefield 2042', category: 'video_games' },
  { text: 'Call of Duty', category: 'video_games' },
  { text: 'Minecraft', category: 'video_games' },
  { text: 'Fortnite', category: 'video_games' },
  { text: 'GTA', category: 'video_games' },
  { text: 'Counter Strike', category: 'video_games' },
  { text: 'Rocket League', category: 'video_games' },
  { text: 'Halo', category: 'video_games' },
  { text: 'Overwatch', category: 'video_games' },
  { text: 'Skyrim', category: 'video_games' },
  { text: 'Elden Ring', category: 'video_games' },
  { text: 'Red Dead Redemption', category: 'video_games' },
  { text: 'The Witcher', category: 'video_games' },
  { text: 'Assassin\'s Creed', category: 'video_games' },
  { text: 'Gaming PC', category: 'tech' },
  { text: 'Laptop', category: 'tech' },
  { text: 'Graphics Card', category: 'tech' },
  { text: 'CPU', category: 'tech' },
  { text: 'RAM', category: 'tech' },
  { text: 'SSD', category: 'tech' },
  { text: 'Hard Drive', category: 'tech' },
  { text: 'Power Supply', category: 'tech' },
  { text: 'Cooling Fan', category: 'tech' },
  { text: 'RGB Lights', category: 'tech' },
  { text: 'Monitor', category: 'tech' },
  { text: 'Gaming Keyboard', category: 'tech' },
  { text: 'Gaming Mouse', category: 'tech' },
  { text: 'Headset', category: 'tech' },
  { text: 'Microphone', category: 'tech' },
  { text: 'Router', category: 'tech' },
  { text: 'WiFi', category: 'tech' },
  { text: 'Ethernet Cable', category: 'tech' },
  { text: 'USB Stick', category: 'tech' },
  { text: 'Printer', category: 'tech' },
  { text: 'Monopoly', category: 'board_games' },
  { text: 'Monopoly Deal', category: 'board_games' },
  { text: 'Rummikub', category: 'board_games' },
  { text: 'Chess', category: 'board_games' },
  { text: 'Checkers', category: 'board_games' },
  { text: 'Scrabble', category: 'board_games' },
  { text: 'Risk', category: 'board_games' },
  { text: 'Clue', category: 'board_games' },
  { text: 'Uno', category: 'board_games' },
  { text: 'Playing Cards', category: 'board_games' },
  { text: 'Mario', category: 'mario_kart' },
  { text: 'Luigi', category: 'mario_kart' },
  { text: 'Princess Peach', category: 'mario_kart' },
  { text: 'Bowser', category: 'mario_kart' },
  { text: 'Toad', category: 'mario_kart' },
  { text: 'Donkey Kong', category: 'mario_kart' },
  { text: 'Yoshi', category: 'mario_kart' },
  { text: 'Wario', category: 'mario_kart' },
  { text: 'Waluigi', category: 'mario_kart' },
  { text: 'Rainbow Road', category: 'mario_kart' },
  { text: 'Blue Shell', category: 'mario_kart' },
  { text: 'Red Shell', category: 'mario_kart' },
  { text: 'Green Shell', category: 'mario_kart' },
  { text: 'Banana Peel', category: 'mario_kart' },
  { text: 'Mushroom Boost', category: 'mario_kart' },
  { text: 'Bullet Bill', category: 'mario_kart' },
  { text: 'Mario Kart', category: 'mario_kart' },
  { text: 'Go Kart', category: 'mario_kart' },
  { text: 'Finish Line', category: 'mario_kart' },
  { text: 'Power Up', category: 'mario_kart' },
  { text: 'Darth Vader', category: 'star_wars' },
  { text: 'Luke Skywalker', category: 'star_wars' },
  { text: 'Han Solo', category: 'star_wars' },
  { text: 'Princess Leia', category: 'star_wars' },
  { text: 'Obi Wan Kenobi', category: 'star_wars' },
  { text: 'Yoda', category: 'star_wars' },
  { text: 'Stormtrooper', category: 'star_wars' },
  { text: 'Lightsaber', category: 'star_wars' },
  { text: 'Death Star', category: 'star_wars' },
  { text: 'Millennium Falcon', category: 'star_wars' },
  { text: 'R2-D2', category: 'star_wars' },
  { text: 'C-3PO', category: 'star_wars' },
  { text: 'Boba Fett', category: 'star_wars' },
  { text: 'Mandalorian', category: 'star_wars' },
  { text: 'Baby Yoda', category: 'star_wars' },
  { text: 'Chewbacca', category: 'star_wars' },
  { text: 'Emperor Palpatine', category: 'star_wars' },
  { text: 'TIE Fighter', category: 'star_wars' },
  { text: 'X-Wing', category: 'star_wars' },
  { text: 'Jedi', category: 'star_wars' },
  { text: 'Sith', category: 'star_wars' },
  { text: 'The Force', category: 'star_wars' },
  { text: 'Clone Trooper', category: 'star_wars' },
  { text: 'Darth Maul', category: 'star_wars' },
  { text: 'Kylo Ren', category: 'star_wars' },
  { text: 'Frodo', category: 'lotr' },
  { text: 'Gandalf', category: 'lotr' },
  { text: 'Aragorn', category: 'lotr' },
  { text: 'Legolas', category: 'lotr' },
  { text: 'Gimli', category: 'lotr' },
  { text: 'Samwise', category: 'lotr' },
  { text: 'Gollum', category: 'lotr' },
  { text: 'The One Ring', category: 'lotr' },
  { text: 'Mordor', category: 'lotr' },
  { text: 'Sauron', category: 'lotr' },
  { text: 'Saruman', category: 'lotr' },
  { text: 'Hobbit', category: 'lotr' },
  { text: 'Orc', category: 'lotr' },
  { text: 'Nazgûl', category: 'lotr' },
  { text: 'Mount Doom', category: 'lotr' },
  { text: 'Taylor Swift', category: 'pop_culture' },
  { text: 'Ed Sheeran', category: 'pop_culture' },
  { text: 'Drake', category: 'pop_culture' },
  { text: 'The Rock', category: 'pop_culture' },
  { text: 'Ryan Reynolds', category: 'pop_culture' },
  { text: 'Keanu Reeves', category: 'pop_culture' },
  { text: 'Leonardo DiCaprio', category: 'pop_culture' },
  { text: 'Elon Musk', category: 'pop_culture' },
  { text: 'Jeff Bezos', category: 'pop_culture' },
  { text: 'Gordon Ramsay', category: 'pop_culture' },
  { text: 'David Beckham', category: 'pop_culture' },
  { text: 'Mr Beast', category: 'pop_culture' },
  { text: 'PewDiePie', category: 'pop_culture' },
  { text: 'Kim Kardashian', category: 'pop_culture' },
  { text: 'Kanye West', category: 'pop_culture' },
  { text: 'Billie Eilish', category: 'pop_culture' },
  { text: 'Tom Cruise', category: 'pop_culture' },
  { text: 'Chris Hemsworth', category: 'pop_culture' },
  { text: 'Will Smith', category: 'pop_culture' },
  { text: 'Zendaya', category: 'pop_culture' },
  { text: 'Pizza', category: 'general' },
  { text: 'Beer', category: 'general' },
  { text: 'Burger', category: 'general' },
  { text: 'Hot Dog', category: 'general' },
  { text: 'Coffee', category: 'general' },
  { text: 'Taxi', category: 'general' },
  { text: 'Police Officer', category: 'general' },
  { text: 'Firefighter', category: 'general' },
  { text: 'Astronaut', category: 'general' },
  { text: 'Pirate', category: 'general' },
  { text: 'Dinosaur', category: 'general' },
  { text: 'Shark', category: 'general' },
  { text: 'Dragon', category: 'general' },
  { text: 'Alien', category: 'general' },
  { text: 'Robot', category: 'general' },
  { text: 'Zombie', category: 'general' },
  { text: 'Ghost', category: 'general' },
  { text: 'Wizard', category: 'general' },
  { text: 'Knight', category: 'general' },
  { text: 'Viking', category: 'general' },
  { text: 'Olympic Games', category: 'general' },
  { text: 'Gold Medal', category: 'general' },
  { text: 'Roller Coaster', category: 'general' },
  { text: 'Theme Park', category: 'general' },
  { text: 'Cinema', category: 'general' },
  { text: 'Popcorn', category: 'general' },
  { text: 'Netflix', category: 'general' },
  { text: 'YouTube', category: 'general' },
  { text: 'Spotify', category: 'general' },
  { text: 'Smartphone', category: 'general' },
  { text: 'Airplane', category: 'general' },
  { text: 'Helicopter', category: 'general' },
  { text: 'Cruise Ship', category: 'general' },
  { text: 'Train', category: 'general' },
  { text: 'Bicycle', category: 'general' },
  { text: 'Skateboard', category: 'general' },
  { text: 'Snowboard', category: 'general' },
  { text: 'Surfboard', category: 'general' },
  { text: 'Parachute', category: 'general' },
  { text: 'Space Rocket', category: 'general' },
]
